asciidoc:
  code:
    language:
      default: text
  template:
    space-key: ":DOCUMENT-SPACE-KEY:"
    title: ":DOCUMENT-TITLE:"
    title-old: ":DOCUMENT-TITLE:-OLD"
    parent: ":DOCUMENT-PARENT:"

server:
  port: 8088

spring:
  main:
    banner-mode: "off"
  profiles:
    active: main

logging:
  #  file: lic-gen.log
  level:
    root: WARN
    ws.slink: TRACE
  pattern:
    console: "%d{dd-MM-yyyy HH:mm:ss.SSS} %magenta([%thread]) %highlight(%-5level) %logger.%M - %msg%n"
