asciidoc:
  code:
    language:
      default: text
  template:
    title: ":DOCUMENT-TITLE:"
    title-old: ":DOCUMENT-TITLE-OLD:"
    parent: ":DOCUMENT-PARENT:"
    hidden: ":DOCUMENT-HIDDEN:"
    tags: ":DOCUMENT-TAGS:"

confluence:
  protected:
    label: ${PROTECTED_LABELS:_dx_kb_keep}
  urls:
    versions: experimental

server:
  port: 8088

spring:
  main:
    banner-mode: "off"
  profiles:
    active: main

logging:
  level:
    root: WARN
    com.dxfeed: ${LOGLEVEL:INFO}
