name: Automated Release

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  generate:
    name: release
    runs-on: ubuntu-latest
    steps:
#      - name: Get current tag
#        id: tag
#        run: ::set-output name=tag::$(echo ${GITHUB_REF:10})
      - uses: actions/checkout@master
      - name: build
        uses: mvkvl/github-action-build@master
        with:
          builder: .github/build
#      - name: publish
#        uses: mvkvl/github-action-publish-binaries@master
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          args: '*-${{ steps.tag.outputs.tag }}'

#  test-action:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Get current tag
#        id: tag
#        run: ::set-output name=tag::$(echo ${GITHUB_REF:10})
#      - name: Check tag
#        run: |
#          echo "RELEASE TAG: ${{ steps.tag.outputs.tag }}"